"""empty message

Revision ID: 9bb719225b5a
Revises: a558a22240db
Create Date: 2018-09-17 06:45:48.913530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb719225b5a'
down_revision = 'a558a22240db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'songs', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'owner_id')
    # ### end Alembic commands ###
